### PR TITLE
initial proposal for maintaining index of content on miners

### PR DESCRIPTION
**Pull request by willscott**
[Rendered](https://github.com/protocol/web3-dev-team/blob/326db514fc6f8748a241a3c93380acf89aa3713d/proposals/miner-indexing.md)

### CODE REVIEW

**Review by hannahhoward — COMMENTED** [review]
I put a comment in slack, but essentially, this project is already done, just not turned on. The miner already has to index root CIDs in cars to the pieces they are in. An already implemented extension writes an index of every CID in every car to the piece that it's a part of. It's just not turned on by default cause of the storage penalty to maintain this index.  https://github.com/filecoin-project/go-fil-markets/pull/166

**Review by mikeal — APPROVED** [review]

**Comment by mikeal** [comment]
given @hannahhoward’s comment would you change the ease rating?

**Comment by willscott** [comment]
nope. I think still at least a medium

**Comment by pooja** [comment]
this project isn't currently in progress, right @willscott ?

**Comment by willscott** [comment]
The sharded dag-store will accomplish the goal outlined in this proposal

**Comment by pooja** [comment]
asking for project pipeline purposes -- since we have another proposal for sharded dag store that is in progress, will move this one to the project backlog (or we can close it if you think it's redundant)

**Pull request closed without merging**
